// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"mall/service/test/internal/logic"
	"mall/service/test/internal/svc"
	"mall/service/test/remote"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	remote.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

//  登录
func (s *UserServer) Login(ctx context.Context, in *remote.Request) (*remote.Response, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
